import type { SttModel, LlmModel } from "../types";

// Base URL for Whisper GGML models on Hugging Face
export const WHISPER_BASE_URL =
  "https://huggingface.co/ggerganov/whisper.cpp/resolve/main/";

// ============================================================
// STT models (Whisper) — from build plan §4
// ============================================================
export const STT_MODELS: SttModel[] = [
  // ── Tiny ──────────────────────────────────────────────────
  {
    id: "tiny.en",
    file: "ggml-tiny.en.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Tiny (English)",
    size_mb: 75,
    ram_mb: 390,
    speed_label: "~10x realtime",
    wer: "~8%",
    multilingual: false,
    preset: "speed",
    best_for: "Speed mode, quick notes",
  },
  {
    id: "tiny",
    file: "ggml-tiny.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Tiny (Multilingual)",
    size_mb: 75,
    ram_mb: 390,
    speed_label: "~10x realtime",
    wer: "~8%",
    multilingual: true,
    preset: "speed",
    best_for: "Speed + multilingual",
  },

  // ── Base ──────────────────────────────────────────────────
  {
    id: "base.en",
    file: "ggml-base.en.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Base (English)",
    size_mb: 142,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~5.5%",
    multilingual: false,
    preset: "balanced",
    best_for: "Balanced English",
  },
  {
    id: "base",
    file: "ggml-base.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Base (Multilingual)",
    size_mb: 142,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~5.5%",
    multilingual: true,
    preset: "balanced",
    best_for: "Balanced multilingual",
  },

  // ── Small ─────────────────────────────────────────────────
  {
    id: "small.en",
    file: "ggml-small.en.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Small (English)",
    size_mb: 466,
    ram_mb: 1024,
    speed_label: "~3x realtime",
    wer: "~3.4%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Good accuracy English",
  },
  {
    id: "small",
    file: "ggml-small.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Small (Multilingual)",
    size_mb: 466,
    ram_mb: 1024,
    speed_label: "~3x realtime",
    wer: "~3.4%",
    multilingual: true,
    preset: "multilingual",
    best_for: "Good accuracy multilingual",
  },

  // ── Medium ────────────────────────────────────────────────
  {
    id: "medium.en",
    file: "ggml-medium.en.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Medium (English)",
    size_mb: 1536,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~2.9%",
    multilingual: false,
    preset: "accuracy",
    best_for: "High accuracy English",
  },
  {
    id: "medium",
    file: "ggml-medium.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Medium (Multilingual)",
    size_mb: 1536,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~2.9%",
    multilingual: true,
    preset: "multilingual",
    best_for: "High accuracy multilingual",
  },

  // ── Large ─────────────────────────────────────────────────
  {
    id: "large-v3-turbo",
    file: "ggml-large-v3-turbo.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Large v3 Turbo",
    size_mb: 1638,
    ram_mb: 3277,
    speed_label: "~0.5x realtime",
    wer: "~2.9%",
    multilingual: true,
    preset: "accuracy",
    best_for: "Near-best accuracy, faster",
  },
  {
    id: "large-v3",
    file: "ggml-large-v3.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Large v3",
    size_mb: 2970,
    ram_mb: 4813,
    speed_label: "~0.3x realtime",
    wer: "~2.5%",
    multilingual: true,
    preset: "multilingual",
    best_for: "Best accuracy (slow on CPU)",
  },
  {
    id: "large-v2",
    file: "ggml-large-v2.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Large v2",
    size_mb: 2970,
    ram_mb: 4813,
    speed_label: "~0.3x realtime",
    wer: "~2.7%",
    multilingual: true,
    preset: "multilingual",
    best_for: "Legacy high accuracy model",
  },
  {
    id: "large-v1",
    file: "ggml-large-v1.bin",
    family: "Whisper",
    provider: "OpenAI",
    label: "Large v1",
    size_mb: 2970,
    ram_mb: 4813,
    speed_label: "~0.3x realtime",
    wer: "~3.0%",
    multilingual: true,
    preset: "multilingual",
    best_for: "Original large model",
  },

  // ── Distil-Whisper (HuggingFace) ──────────────────────────
  {
    id: "distil-large-v3.5",
    file: "ggml-distil-large-v3.5.bin",
    family: "Distil-Whisper",
    provider: "Hugging Face",
    label: "Distil Large v3.5",
    size_mb: 756,
    ram_mb: 1500,
    speed_label: "~3x realtime",
    wer: "~3.0%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Fast + accurate English (6x faster than Large)",
    url: "https://huggingface.co/distil-whisper/distil-large-v3.5-ggml/resolve/main/ggml-distil-large-v3.5.bin",
  },
  {
    id: "distil-large-v3",
    file: "ggml-distil-large-v3.bin",
    family: "Distil-Whisper",
    provider: "Hugging Face",
    label: "Distil Large v3",
    size_mb: 756,
    ram_mb: 1500,
    speed_label: "~2.5x realtime",
    wer: "~3.2%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Fast + accurate English (distilled)",
    url: "https://huggingface.co/distil-whisper/distil-large-v3-ggml/resolve/main/ggml-distil-large-v3.bin",
  },

  // ── Chinese (Mandarin) ────────────────────────────────────
  {
    id: "belle-whisper-large-v3-turbo-zh",
    file: "ggml-belle-whisper-large-v3-turbo-zh.bin",
    family: "Whisper",
    provider: "BELLE-2",
    label: "Belle Whisper Large v3 Turbo (Chinese)",
    size_mb: 1625,
    ram_mb: 3277,
    speed_label: "~0.5x realtime",
    wer: "~2.9%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Best-in-class Mandarin Chinese accuracy",
    url: "https://huggingface.co/BELLE-2/Belle-whisper-large-v3-turbo-zh-ggml/resolve/main/ggml-model.bin",
  },

  // ── Japanese ──────────────────────────────────────────────
  {
    id: "kotoba-whisper-v1.0",
    file: "ggml-kotoba-whisper-v1.0.bin",
    family: "Distil-Whisper",
    provider: "Kotoba Technologies",
    label: "Kotoba Whisper v1.0 (Japanese)",
    size_mb: 1520,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~2.9%",
    multilingual: false,
    preset: "accuracy",
    best_for: "High-accuracy Japanese ASR (distilled)",
    url: "https://huggingface.co/kotoba-tech/kotoba-whisper-v1.0-ggml/resolve/main/ggml-kotoba-whisper-v1.0.bin",
  },
  {
    id: "kotoba-whisper-v1.0-q5_0",
    file: "ggml-kotoba-whisper-v1.0-q5_0.bin",
    family: "Distil-Whisper",
    provider: "Kotoba Technologies",
    label: "Kotoba Whisper v1.0 Q5 (Japanese)",
    size_mb: 538,
    ram_mb: 1100,
    speed_label: "~2x realtime",
    wer: "~3.2%",
    multilingual: false,
    preset: "balanced",
    best_for: "Fast Japanese ASR, quantized for modest CPUs",
    url: "https://huggingface.co/kotoba-tech/kotoba-whisper-v1.0-ggml/resolve/main/ggml-kotoba-whisper-v1.0-q5_0.bin",
  },
  {
    id: "kotoba-whisper-v2.0",
    file: "ggml-kotoba-whisper-v2.0.bin",
    family: "Distil-Whisper",
    provider: "Kotoba Technologies",
    label: "Kotoba Whisper v2.0 (Japanese)",
    size_mb: 1520,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~2.8%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Improved Japanese accuracy over v1.0",
    url: "https://huggingface.co/kotoba-tech/kotoba-whisper-v2.0-ggml/resolve/main/ggml-kotoba-whisper-v2.0.bin",
  },
  {
    id: "kotoba-whisper-v2.0-q5_0",
    file: "ggml-kotoba-whisper-v2.0-q5_0.bin",
    family: "Distil-Whisper",
    provider: "Kotoba Technologies",
    label: "Kotoba Whisper v2.0 Q5 (Japanese)",
    size_mb: 538,
    ram_mb: 1100,
    speed_label: "~2x realtime",
    wer: "~3.1%",
    multilingual: false,
    preset: "balanced",
    best_for: "Lightweight fast Japanese ASR",
    url: "https://huggingface.co/kotoba-tech/kotoba-whisper-v2.0-ggml/resolve/main/ggml-kotoba-whisper-v2.0-q5_0.bin",
  },
  {
    id: "ivydata-whisper-base-ja",
    file: "ggml-ivydata-whisper-base-ja.bin",
    family: "Whisper",
    provider: "Ivydata",
    label: "Ivydata Whisper Base (Japanese)",
    size_mb: 148,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~5.5%",
    multilingual: false,
    preset: "speed",
    best_for: "Lightweight Japanese ASR for low-RAM machines",
    url: "https://huggingface.co/Marksdo/WhisperMate/resolve/main/ggml-base-Ivydata.ja.bin",
  },
  {
    id: "reazonspeech-distil-large-v3-ja",
    file: "ggml-reazonspeech-distil-large-v3-ja.bin",
    family: "Distil-Whisper",
    provider: "ReazonSpeech",
    label: "ReazonSpeech Distil Large v3 (Japanese)",
    size_mb: 1520,
    ram_mb: 2662,
    speed_label: "~2x realtime",
    wer: "~2.8%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Fast, accurate Japanese — trained on a huge native speech corpus",
    url: "https://huggingface.co/Marksdo/WhisperMate/resolve/main/ggml-distil-large-v3-reazonspeech.ja.bin",
  },
  {
    id: "anime-whisper-ggml",
    file: "ggml-anime-whisper-ggml.bin",
    family: "Distil-Whisper",
    provider: "Aratako",
    label: "Anime Whisper (Japanese)",
    size_mb: 1520,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~3.5%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Anime & fast colloquial Japanese dialogue transcription",
    url: "https://huggingface.co/Aratako/anime-whisper-ggml/resolve/main/ggml-anime-whisper.bin",
  },
  {
    id: "anime-whisper-q5_0",
    file: "ggml-anime-whisper-q5_0.bin",
    family: "Distil-Whisper",
    provider: "Aratako",
    label: "Anime Whisper Q5 (Japanese)",
    size_mb: 538,
    ram_mb: 1100,
    speed_label: "~2x realtime",
    wer: "~3.8%",
    multilingual: false,
    preset: "balanced",
    best_for: "Fast anime-style Japanese transcription",
    url: "https://huggingface.co/Aratako/anime-whisper-ggml/resolve/main/ggml-anime-whisper-q5_0.bin",
  },

  // ── Cantonese ─────────────────────────────────────────────
  {
    id: "whisper-base-cantonese",
    file: "ggml-whisper-base-cantonese.bin",
    family: "Whisper",
    provider: "wabisabisocial",
    label: "Whisper Base (Cantonese)",
    size_mb: 148,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~6%",
    multilingual: false,
    preset: "speed",
    best_for: "Lightweight Cantonese (Yue Chinese) ASR",
    url: "https://huggingface.co/wabisabisocial/whisper-base-cantonese-ggml/resolve/main/ggml-base-yue.bin",
  },
  {
    id: "whisper-large-v3-cantonese-q8_0",
    file: "ggml-whisper-large-v3-cantonese-q8_0.bin",
    family: "Whisper",
    provider: "kiuckhuang",
    label: "Whisper Large v3 Q8 (Cantonese)",
    size_mb: 1657,
    ram_mb: 3277,
    speed_label: "~0.5x realtime",
    wer: "~3%",
    multilingual: false,
    preset: "accuracy",
    best_for: "High-accuracy Cantonese with manageable RAM",
    url: "https://huggingface.co/kiuckhuang/whisper-large-v3-cantonese-ggml/resolve/main/whisper-large-v3-cantonese.q8_0.bin",
  },

  // ── Korean ────────────────────────────────────────────────
  {
    id: "whisper-medium-korean-royshilkrot",
    file: "ggml-whisper-medium-korean-royshilkrot.bin",
    family: "Whisper",
    provider: "royshilkrot",
    label: "Whisper Medium (Korean)",
    size_mb: 1534,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~3%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Solid general-purpose Korean ASR",
    url: "https://huggingface.co/royshilkrot/whisper-medium-korean-ggml/resolve/main/whisper-medium-korean.bin",
  },
  {
    id: "whisper-base-sungbeom-ko",
    file: "ggml-whisper-base-sungbeom-ko.bin",
    family: "Whisper",
    provider: "SungBeom",
    label: "Whisper Base (Korean)",
    size_mb: 148,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~6%",
    multilingual: false,
    preset: "speed",
    best_for: "Lightweight Korean ASR",
    url: "https://huggingface.co/Marksdo/WhisperMate/resolve/main/ggml-base-sungbeom.ko.bin",
  },
  {
    id: "whisper-base-komixv2-seastar105-ko",
    file: "ggml-whisper-base-komixv2-seastar105-ko.bin",
    family: "Whisper",
    provider: "seastar105",
    label: "Whisper Base KomixV2 (Korean)",
    size_mb: 148,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~5.8%",
    multilingual: false,
    preset: "speed",
    best_for: "Lightweight Korean ASR, diverse dataset fine-tune",
    url: "https://huggingface.co/Marksdo/WhisperMate/resolve/main/ggml-base-komixv2-seastar105.ko.bin",
  },

  // ── Vietnamese ────────────────────────────────────────────
  {
    id: "phowhisper-medium-vi",
    file: "ggml-phowhisper-medium-vi.bin",
    family: "Whisper",
    provider: "VinAI Research",
    label: "PhoWhisper Medium (Vietnamese)",
    size_mb: 1534,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~4%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Best-in-class Vietnamese ASR across accents",
    url: "https://huggingface.co/dongxiat/ggml-PhoWhisper-medium/resolve/main/ggml-PhoWhisper-medium.bin",
  },

  // ── Polish ────────────────────────────────────────────────
  {
    id: "whisper-polish-medium",
    file: "ggml-whisper-polish-medium.bin",
    family: "Whisper",
    provider: "knightdave",
    label: "Whisper Medium (Polish)",
    size_mb: 1534,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~4%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Balanced quality/speed Polish transcription",
    url: "https://huggingface.co/knightdave/whisper-polish-ggml-handy/resolve/main/ggml-medium-pl.bin",
  },
  {
    id: "whisper-polish-small",
    file: "ggml-whisper-polish-small.bin",
    family: "Whisper",
    provider: "knightdave",
    label: "Whisper Small (Polish)",
    size_mb: 488,
    ram_mb: 1024,
    speed_label: "~3x realtime",
    wer: "~5%",
    multilingual: false,
    preset: "balanced",
    best_for: "Fast Polish transcription, lower RAM",
    url: "https://huggingface.co/knightdave/whisper-polish-ggml-handy/resolve/main/ggml-small-pl.bin",
  },
  {
    id: "whisper-polish-large-v2",
    file: "ggml-whisper-polish-large-v2.bin",
    family: "Whisper",
    provider: "knightdave",
    label: "Whisper Large v2 (Polish)",
    size_mb: 3095,
    ram_mb: 4813,
    speed_label: "~0.3x realtime",
    wer: "~3%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Highest-accuracy Polish transcription",
    url: "https://huggingface.co/knightdave/whisper-polish-ggml-handy/resolve/main/ggml-large-v2-pl.bin",
  },

  // ── Portuguese ────────────────────────────────────────────
  {
    id: "whisper-medium-portuguese-gustrd",
    file: "ggml-whisper-medium-portuguese-gustrd.bin",
    family: "Whisper",
    provider: "Gustrd",
    label: "Whisper Medium (Portuguese)",
    size_mb: 1534,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~3.5%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Strong European/Brazilian Portuguese accuracy",
    url: "https://huggingface.co/Gustrd/whisper-medium-portuguese-ggml-model/resolve/main/whisper-medium-portuguese-ggml-model.bin",
  },

  // ── German ────────────────────────────────────────────────
  {
    id: "whisper-large-v3-turbo-german",
    file: "ggml-whisper-large-v3-turbo-german.bin",
    family: "Whisper",
    provider: "cstr",
    label: "Whisper Large v3 Turbo (German)",
    size_mb: 1625,
    ram_mb: 3277,
    speed_label: "~0.5x realtime",
    wer: "~2.5%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Fast, high-accuracy German ASR",
    url: "https://huggingface.co/cstr/whisper-large-v3-turbo-german-ggml/resolve/main/ggml-model.bin",
  },
  {
    id: "whisper-large-v3-turbo-german-q5_0",
    file: "ggml-whisper-large-v3-turbo-german-q5_0.bin",
    family: "Whisper",
    provider: "cstr",
    label: "Whisper Large v3 Turbo Q5 (German)",
    size_mb: 574,
    ram_mb: 1200,
    speed_label: "~1.5x realtime",
    wer: "~2.8%",
    multilingual: false,
    preset: "balanced",
    best_for: "Fast German ASR on limited RAM",
    url: "https://huggingface.co/cstr/whisper-large-v3-turbo-german-ggml/resolve/main/ggml-model-q5_0.bin",
  },

  // ── French ────────────────────────────────────────────────
  {
    id: "whisper-large-v3-french-bofenghuang",
    file: "ggml-whisper-large-v3-french-bofenghuang.bin",
    family: "Whisper",
    provider: "Bofeng Huang",
    label: "Whisper Large v3 (French)",
    size_mb: 3095,
    ram_mb: 4813,
    speed_label: "~0.3x realtime",
    wer: "~2.5%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Best-in-class French accuracy",
    url: "https://huggingface.co/bofenghuang/whisper-large-v3-french/resolve/main/ggml-model.bin",
  },
  {
    id: "whisper-large-v3-french-bofenghuang-q5_0",
    file: "ggml-whisper-large-v3-french-bofenghuang-q5_0.bin",
    family: "Whisper",
    provider: "Bofeng Huang",
    label: "Whisper Large v3 Q5 (French)",
    size_mb: 1081,
    ram_mb: 2100,
    speed_label: "~0.8x realtime",
    wer: "~2.8%",
    multilingual: false,
    preset: "accuracy",
    best_for: "High-quality French ASR, reduced RAM",
    url: "https://huggingface.co/bofenghuang/whisper-large-v3-french/resolve/main/ggml-model-q5_0.bin",
  },

  // ── Russian ───────────────────────────────────────────────
  {
    id: "whisper-large-v3-russian-limtech",
    file: "ggml-whisper-large-v3-russian-limtech.bin",
    family: "Whisper",
    provider: "Limtech",
    label: "Whisper Large v3 (Russian)",
    size_mb: 3095,
    ram_mb: 4813,
    speed_label: "~0.3x realtime",
    wer: "~3%",
    multilingual: false,
    preset: "accuracy",
    best_for: "High-accuracy Russian transcription",
    url: "https://huggingface.co/Limtech/whisper-large-v3-russian-ggml/resolve/main/ggml-model.bin",
  },

  // ── Arabic ────────────────────────────────────────────────
  {
    id: "whisper-large-v3-arabic-mohamedrashad",
    file: "ggml-whisper-large-v3-arabic-mohamedrashad.bin",
    family: "Whisper",
    provider: "MohamedRashad",
    label: "Whisper Large (Arabic)",
    size_mb: 3095,
    ram_mb: 4813,
    speed_label: "~0.3x realtime",
    wer: "~3.5%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Best-in-class Modern Standard Arabic accuracy",
    url: "https://huggingface.co/Marksdo/WhisperMate/resolve/main/ggml-large-MohamedRashad.ar.bin",
  },
  {
    id: "whisper-large-v3-arabic-q5_0",
    file: "ggml-whisper-large-v3-arabic-q5_0.bin",
    family: "Whisper",
    provider: "Pomni",
    label: "Whisper Large v3 Q5 (Arabic)",
    size_mb: 1081,
    ram_mb: 2100,
    speed_label: "~0.8x realtime",
    wer: "~3.8%",
    multilingual: false,
    preset: "accuracy",
    best_for: "High-quality Arabic ASR, moderate RAM",
    url: "https://huggingface.co/Pomni/whisper-large-v3-arabic-ggml-allquants/resolve/main/ggml-large-v3-arabic-q5_0.bin",
  },
  {
    id: "whisper-large-v3-arabic-q4_0",
    file: "ggml-whisper-large-v3-arabic-q4_0.bin",
    family: "Whisper",
    provider: "Pomni",
    label: "Whisper Large v3 Q4 (Arabic)",
    size_mb: 889,
    ram_mb: 1800,
    speed_label: "~1x realtime",
    wer: "~4.2%",
    multilingual: false,
    preset: "balanced",
    best_for: "Compact Arabic ASR for lower RAM",
    url: "https://huggingface.co/Pomni/whisper-large-v3-arabic-ggml-allquants/resolve/main/ggml-large-v3-arabic-q4_0.bin",
  },
  {
    id: "whisper-base-arabic-quran",
    file: "ggml-whisper-base-arabic-quran.bin",
    family: "Whisper",
    provider: "Community",
    label: "Whisper Base (Quranic Arabic)",
    size_mb: 148,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~6%",
    multilingual: false,
    preset: "speed",
    best_for: "Quranic Arabic recitation transcription",
    url: "https://huggingface.co/Marksdo/WhisperMate/resolve/main/ggml-base-quran.ar.bin",
  },

  // ── Hebrew ────────────────────────────────────────────────
  {
    id: "whisper-medium-hebrew-imvladikon",
    file: "ggml-whisper-medium-hebrew-imvladikon.bin",
    family: "Whisper",
    provider: "imvladikon",
    label: "Whisper Medium (Hebrew)",
    size_mb: 1534,
    ram_mb: 2662,
    speed_label: "~1x realtime",
    wer: "~4%",
    multilingual: false,
    preset: "accuracy",
    best_for: "Best-available Hebrew ASR",
    url: "https://huggingface.co/imvladikon/whisper-medium-he/resolve/main/ggml-hebrew.bin",
  },

  // ── Norwegian ─────────────────────────────────────────────
  {
    id: "nb-whisper-base-norwegian",
    file: "ggml-nb-whisper-base-norwegian.bin",
    family: "Whisper",
    provider: "National Library of Norway AI Lab",
    label: "NB-Whisper Base (Norwegian)",
    size_mb: 148,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~5%",
    multilingual: false,
    preset: "speed",
    best_for: "Solid Norwegian (Bokmål) ASR from a national library lab",
    url: "https://huggingface.co/NbAiLabBeta/nb-whisper-base/resolve/main/ggml-model.bin",
  },
  {
    id: "nb-whisper-base-norwegian-q5_0",
    file: "ggml-nb-whisper-base-norwegian-q5_0.bin",
    family: "Whisper",
    provider: "National Library of Norway AI Lab",
    label: "NB-Whisper Base Q5 (Norwegian)",
    size_mb: 55,
    ram_mb: 300,
    speed_label: "~10x realtime",
    wer: "~5.5%",
    multilingual: false,
    preset: "speed",
    best_for: "Extremely lightweight Norwegian ASR",
    url: "https://huggingface.co/NbAiLabBeta/nb-whisper-base/resolve/main/ggml-model-q5_0.bin",
  },

  // ── Swedish ───────────────────────────────────────────────
  {
    id: "kb-whisper-base-swedish",
    file: "ggml-kb-whisper-base-swedish.bin",
    family: "Whisper",
    provider: "KBLab (National Library of Sweden)",
    label: "KB-Whisper Base (Swedish)",
    size_mb: 148,
    ram_mb: 500,
    speed_label: "~7x realtime",
    wer: "~5%",
    multilingual: false,
    preset: "speed",
    best_for: "Solid Swedish ASR from a national library lab",
    url: "https://huggingface.co/KBLab/kb-whisper-base/resolve/main/ggml-model.bin",
  },
  {
    id: "kb-whisper-base-swedish-q5_0",
    file: "ggml-kb-whisper-base-swedish-q5_0.bin",
    family: "Whisper",
    provider: "KBLab (National Library of Sweden)",
    label: "KB-Whisper Base Q5 (Swedish)",
    size_mb: 55,
    ram_mb: 300,
    speed_label: "~10x realtime",
    wer: "~5.5%",
    multilingual: false,
    preset: "speed",
    best_for: "Extremely lightweight Swedish ASR",
    url: "https://huggingface.co/KBLab/kb-whisper-base/resolve/main/ggml-model-q5_0.bin",
  },

  // ── Multilingual (community quantizations) ───────────────
  {
    id: "whisper-large-v2-allquants-q5_0",
    file: "ggml-whisper-large-v2-allquants-q5_0.bin",
    family: "Whisper",
    provider: "Pomni",
    label: "Whisper Large v2 Q5 (Multilingual)",
    size_mb: 1081,
    ram_mb: 2100,
    speed_label: "~0.8x realtime",
    wer: "~2.9%",
    multilingual: true,
    preset: "multilingual",
    best_for: "High-quality multilingual (99 languages), reduced RAM vs full large-v2",
    url: "https://huggingface.co/Pomni/whisper-large-v2-ggml-allquants/resolve/main/ggml-large-v2-q5_0.bin",
  },
  {
    id: "whisper-large-v2-allquants-q3_k",
    file: "ggml-whisper-large-v2-allquants-q3_k.bin",
    family: "Whisper",
    provider: "Pomni",
    label: "Whisper Large v2 Q3 (Multilingual)",
    size_mb: 685,
    ram_mb: 1500,
    speed_label: "~1.2x realtime",
    wer: "~3.3%",
    multilingual: true,
    preset: "multilingual",
    best_for: "Aggressively compressed multilingual large-class model, lowest RAM",
    url: "https://huggingface.co/Pomni/whisper-large-v2-ggml-allquants/resolve/main/ggml-large-v2-q3_k.bin",
  },
];

// ============================================================
// LLM models (AI processing) — from build plan §5
// ============================================================
export const LLM_MODELS: LlmModel[] = [
  // ── Tiny tier (≤ 2B, runs anywhere) ───────────────────────
  {
    id: "llama-3.2-1b-instruct-q4",
    name: "Llama 3.2 1B Instruct",
    provider: "Meta",
    url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf",
    params: "1B",
    size_mb: 770,
    ram_gb: 1.5,
    tier: "tiny",
    speed_label: "~20 tok/s CPU",
    languages: "Multilingual",
    license: "Llama 3.2",
    best_for: "Fast cleanup, quick edits",
  },
  {
    id: "gemma-3-1b-it-q4",
    name: "Gemma 3 1B",
    provider: "Google",
    url: "https://huggingface.co/ggml-org/gemma-3-1b-it-GGUF/resolve/main/gemma-3-1b-it-Q4_K_M.gguf",
    params: "1B",
    size_mb: 769,
    ram_gb: 1.5,
    tier: "tiny",
    speed_label: "~22 tok/s CPU",
    languages: "Multilingual",
    license: "Gemma",
    best_for: "Basic cleanup",
  },
  {
    id: "qwen2.5-1.5b-instruct-q4",
    name: "Qwen 2.5 1.5B Instruct",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf",
    params: "1.5B",
    size_mb: 1066,
    ram_gb: 2.0,
    tier: "tiny",
    speed_label: "~16 tok/s CPU",
    languages: "Multilingual",
    license: "Apache-2.0",
    best_for: "Multilingual cleanup",
  },
  {
    id: "smollm2-1.7b-instruct-q4",
    name: "SmolLM2 1.7B Instruct",
    provider: "Hugging Face",
    url: "https://huggingface.co/bartowski/SmolLM2-1.7B-Instruct-GGUF/resolve/main/SmolLM2-1.7B-Instruct-Q4_K_M.gguf",
    params: "1.7B",
    size_mb: 1060,
    ram_gb: 2.0,
    tier: "tiny",
    speed_label: "~18 tok/s CPU",
    languages: "English+",
    license: "Apache-2.0",
    best_for: "Lightweight English text cleanup",
  },

  // ── Small tier (2B–4B, 4GB+ RAM) ─────────────────────────
  {
    id: "llama-3.2-3b-instruct-q4",
    name: "Llama 3.2 3B Instruct",
    provider: "Meta",
    url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf",
    params: "3B",
    size_mb: 1926,
    ram_gb: 3.5,
    tier: "small",
    speed_label: "~10 tok/s CPU",
    languages: "Multilingual",
    license: "Llama 3.2",
    best_for: "Balanced quality cleanup",
  },
  {
    id: "qwen2.5-3b-instruct-q4",
    name: "Qwen 2.5 3B Instruct",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf",
    params: "3B",
    size_mb: 2008,
    ram_gb: 3.5,
    tier: "small",
    speed_label: "~9 tok/s CPU",
    languages: "Multilingual",
    license: "Qwen",
    best_for: "Strong multilingual rewriting",
  },
  {
    id: "phi-3.5-mini-instruct-q4",
    name: "Phi-3.5-mini Instruct",
    provider: "Microsoft",
    url: "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF/resolve/main/Phi-3.5-mini-instruct-Q4_K_M.gguf",
    params: "3.8B",
    size_mb: 2283,
    ram_gb: 3.5,
    tier: "small",
    speed_label: "~8 tok/s CPU",
    languages: "English+",
    license: "MIT",
    best_for: "Best small model for careful edits",
  },
  {
    id: "gemma-3-4b-it-q4",
    name: "Gemma 3 4B",
    provider: "Google",
    url: "https://huggingface.co/bartowski/google_gemma-3-4b-it-GGUF/resolve/main/google_gemma-3-4b-it-Q4_K_M.gguf",
    params: "4B",
    size_mb: 2500,
    ram_gb: 4.0,
    tier: "small",
    speed_label: "~7 tok/s CPU",
    languages: "Multilingual",
    license: "Gemma",
    best_for: "Excellent instruction following",
  },
  {
    id: "phi-4-mini-instruct-q4",
    name: "Phi-4-mini Instruct",
    provider: "Microsoft",
    url: "https://huggingface.co/bartowski/microsoft_Phi-4-mini-instruct-GGUF/resolve/main/microsoft_Phi-4-mini-instruct-Q4_K_M.gguf",
    params: "3.8B",
    size_mb: 2490,
    ram_gb: 4.0,
    tier: "small",
    speed_label: "~7 tok/s CPU",
    languages: "English+",
    license: "MIT",
    best_for: "Advanced reasoning in a small model",
  },
  {
    id: "qwen3-4b-q4",
    name: "Qwen3 4B",
    provider: "Alibaba",
    url: "https://huggingface.co/bartowski/Qwen_Qwen3-4B-GGUF/resolve/main/Qwen_Qwen3-4B-Q4_K_M.gguf",
    params: "4B",
    size_mb: 2600,
    ram_gb: 4.0,
    tier: "small",
    speed_label: "~7 tok/s CPU",
    languages: "Multilingual",
    license: "Apache-2.0",
    best_for: "Latest-gen multilingual processing",
  },

  // ── Medium tier (7B–9B, 8GB+ RAM) ────────────────────────
  {
    id: "llama-3.1-8b-instruct-q4",
    name: "Llama 3.1 8B Instruct",
    provider: "Meta",
    url: "https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
    params: "8B",
    size_mb: 4920,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~5 tok/s CPU",
    languages: "Multilingual",
    license: "Llama 3.1",
    best_for: "High-quality general-purpose editing",
  },
  {
    id: "mistral-7b-instruct-v0.3-q4",
    name: "Mistral 7B Instruct v0.3",
    provider: "Mistral AI",
    url: "https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
    params: "7B",
    size_mb: 4370,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~5 tok/s CPU",
    languages: "Multilingual",
    license: "Apache-2.0",
    best_for: "Excellent European language support",
  },
  {
    id: "qwen2.5-7b-instruct-q4",
    name: "Qwen 2.5 7B Instruct",
    provider: "Alibaba",
    url: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF/resolve/main/qwen2.5-7b-instruct-q4_k_m.gguf",
    params: "7B",
    size_mb: 4680,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~5 tok/s CPU",
    languages: "Multilingual",
    license: "Apache-2.0",
    best_for: "Top-tier multilingual rewriting",
  },
  {
    id: "qwen3-8b-q4",
    name: "Qwen3 8B",
    provider: "Alibaba",
    url: "https://huggingface.co/bartowski/Qwen_Qwen3-8B-GGUF/resolve/main/Qwen_Qwen3-8B-Q4_K_M.gguf",
    params: "8B",
    size_mb: 4900,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~4 tok/s CPU",
    languages: "Multilingual",
    license: "Apache-2.0",
    best_for: "Latest-gen thinking & reasoning",
  },
  {
    id: "gemma-3-8b-it-q4",
    name: "Gemma 3 8B",
    provider: "Google",
    url: "https://huggingface.co/bartowski/google_gemma-3-8b-it-GGUF/resolve/main/google_gemma-3-8b-it-Q4_K_M.gguf",
    params: "8B",
    size_mb: 5000,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~4 tok/s CPU",
    languages: "Multilingual",
    license: "Gemma",
    best_for: "Strong all-rounder from Google",
  },
  {
    id: "deepseek-r1-distill-qwen-7b-q4",
    name: "DeepSeek R1 Distill 7B",
    provider: "DeepSeek",
    url: "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-7B-GGUF/resolve/main/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
    params: "7B",
    size_mb: 4680,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~4 tok/s CPU",
    languages: "Multilingual",
    license: "MIT",
    best_for: "Best-in-class reasoning & chain-of-thought",
  },
  {
    id: "yi-1.5-6b-chat-q4",
    name: "Yi-1.5 6B Chat",
    provider: "01.AI",
    url: "https://huggingface.co/bartowski/Yi-1.5-6B-Chat-GGUF/resolve/main/Yi-1.5-6B-Chat-Q4_K_M.gguf",
    params: "6B",
    size_mb: 3800,
    ram_gb: 6.0,
    tier: "medium",
    speed_label: "~6 tok/s CPU",
    languages: "English + Chinese",
    license: "Apache-2.0",
    best_for: "English-Chinese bilingual processing",
  },
  {
    id: "internlm2.5-7b-chat-q4",
    name: "InternLM2.5 7B Chat",
    provider: "Shanghai AI Lab",
    url: "https://huggingface.co/bartowski/internlm2_5-7b-chat-GGUF/resolve/main/internlm2_5-7b-chat-Q4_K_M.gguf",
    params: "7B",
    size_mb: 4680,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~5 tok/s CPU",
    languages: "Multilingual",
    license: "Apache-2.0",
    best_for: "Strong reasoning from China's top lab",
  },
  {
    id: "glm-4-9b-chat-q4",
    name: "GLM-4 9B Chat",
    provider: "Zhipu AI",
    url: "https://huggingface.co/bartowski/glm-4-9b-chat-GGUF/resolve/main/glm-4-9b-chat-Q4_K_M.gguf",
    params: "9B",
    size_mb: 5500,
    ram_gb: 9.0,
    tier: "medium",
    speed_label: "~3 tok/s CPU",
    languages: "English + Chinese",
    license: "GLM-4",
    best_for: "Chinese language excellence",
  },
  {
    id: "llama-3.3-8b-instruct-q4",
    name: "Llama 3.3 8B Instruct",
    provider: "Meta",
    url: "https://huggingface.co/bartowski/allura-forge_Llama-3.3-8B-Instruct-GGUF/resolve/main/allura-forge_Llama-3.3-8B-Instruct-Q4_K_M.gguf",
    params: "8B",
    size_mb: 4920,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~5 tok/s CPU",
    languages: "Multilingual",
    license: "Llama 3.3",
    best_for: "Latest Llama with improved reasoning",
  },
  {
    id: "mistral-nemo-instruct-2407-q4",
    name: "Mistral Nemo 12B Instruct",
    provider: "Mistral AI",
    url: "https://huggingface.co/bartowski/Mistral-Nemo-Instruct-2407-GGUF/resolve/main/Mistral-Nemo-Instruct-2407-Q4_K_M.gguf",
    params: "12B",
    size_mb: 7150,
    ram_gb: 12.0,
    tier: "medium",
    speed_label: "~3 tok/s CPU",
    languages: "Multilingual",
    license: "Apache-2.0",
    best_for: "Premium quality French AI processing",
  },
  {
    id: "deepseek-r1-distill-llama-8b-q4",
    name: "DeepSeek R1 Distill Llama 8B",
    provider: "DeepSeek",
    url: "https://huggingface.co/bartowski/DeepSeek-R1-Distill-Llama-8B-GGUF/resolve/main/DeepSeek-R1-Distill-Llama-8B-Q4_K_M.gguf",
    params: "8B",
    size_mb: 4920,
    ram_gb: 8.0,
    tier: "medium",
    speed_label: "~4 tok/s CPU",
    languages: "Multilingual",
    license: "MIT",
    best_for: "Reasoning-focused text cleanup",
  },
];

// Human-readable language of an STT model, derived from its label/flags — used
// to power the Model Store language filter. Language-specific models put the
// language in parentheses in their label (e.g. "… (Chinese)"); OpenAI base
// models are either "(English)"/"(Multilingual)" or the plain large models
// (multilingual). Distil models are English.
export function sttLanguage(m: SttModel): string {
  const paren = m.label.match(/\(([^)]+)\)/);
  if (paren) {
    const inner = paren[1].trim();
    if (/multilingual/i.test(inner)) return "Multilingual";
    // "Quranic Arabic" -> "Arabic" so it groups with other Arabic models.
    return inner.replace(/^Quranic\s+/i, "");
  }
  return m.multilingual ? "Multilingual" : "English";
}

// Top 20 prioritized languages — build plan §10
export const LANGUAGES: { code: string; name: string }[] = [
  { code: "auto", name: "Auto-detect" },
  { code: "en", name: "English" },
  { code: "zh", name: "Mandarin Chinese" },
  { code: "hi", name: "Hindi" },
  { code: "es", name: "Spanish" },
  { code: "fr", name: "French" },
  { code: "ar", name: "Arabic" },
  { code: "bn", name: "Bengali" },
  { code: "pt", name: "Portuguese" },
  { code: "ru", name: "Russian" },
  { code: "ja", name: "Japanese" },
  { code: "de", name: "German" },
  { code: "ko", name: "Korean" },
  { code: "tr", name: "Turkish" },
  { code: "vi", name: "Vietnamese" },
  { code: "it", name: "Italian" },
  { code: "th", name: "Thai" },
  { code: "nl", name: "Dutch" },
  { code: "pl", name: "Polish" },
  { code: "uk", name: "Ukrainian" },
  { code: "id", name: "Indonesian" },
];
